### ISSUE TITLE
Support Maven 3.1

### ISSUE THREAD

**Issue by bmatthews68** [bmatthews68/ldap-maven-plugin#12]
The 1.2.x versions of LDAP Maven Plugin are using a 3rd party library (Jcabi) to resolve the server implementation dependencies at run-time. This library does not support the latest versions of Aether used by Maven 3.1.

Ideally a future version of Jcabi will support the versions of Aether using in 3.0.x and 3.1.x+. In that case we will be able to maintain backwards compatibility. Otherwise, we will have to drop support for Maven 3.0.5 and use the later version of Aether directly.

**Comment by eeichinger** [comment]
while dynamically resolving the required libs is nice, may I suggest to simple use Maven's default mechanism of <plugin><dependencies> to put the necessary server libs on the plugin classpath? This eliminates a nasty and obviously incompatible dependency

**Comment by marsv024** [comment]
Any update on this?

**Comment by bmatthews68** [comment]
Updated plugin to work with all Maven versions 3.0.5 or higher by removing reliance on jcabi-aether and using Maven APIs to resolve dependencies.
