### ISSUE TITLE
Unit tests fail out of the box

### ISSUE THREAD

**Issue by dagguh** [bmatthews68/ldap-maven-plugin#24]
`mvn test` fails:
```
[ERROR] Failed to execute goal on project server-opendj: Could not resolve dependencies for project com.btmatthews.maven.plugins.ldap:server-opendj:jar:1.3.1-SNAPSHOT: Failure to find org.forgerock.opendj:opendj-ldap-sdk:jar:2.6.0 in https://maven.atlassian.com/content/groups/internal was cached in the local repository, resolution will not be reattempted until the update interval of maven-atlassian-com has elapsed or updates are forced -> [Help 1]
```

**Comment by dagguh** [comment]
What is the reason for closing the issue?

**Comment by bmatthews68** [comment]
If you are using OpenDJ or building from scratch you need to add the ForgeRock repository to your settings.xml. Checkout the bottom of https://github.com/bmatthews68/ldap-maven-plugin

**Comment by dagguh** [comment]
I understand.
However, Maven is designed to minimize tribal knowledge and manual setups.
I added a pull request, which makes OpenDJ work out of the box, without the need to read README or configure XML files.
